### ISSUE TITLE
Jwt checker tool: CLI to test jwt.io libraries for compliance

### ISSUE THREAD

**Issue by pose** [jsonwebtoken/jsonwebtoken.github.io#101]

**Comment by sebadoom** [comment]
While having a simple CLI tool would be convenient, I don't think it can help us much for the libraries. Each library has a different API and tests must be coded for each of them (against our implementation, be it a CLI tool or something else).

In general I think given the lack of time the right approach is to add a library and report what it supports according to its docs. If the library's docs are wrong we will get a bug report here and update accordingly. This is what we have been doing ever since the site went online.
