### ISSUE TITLE
Feature Request: Shareable URL

### ISSUE THREAD

**Issue by colllin** [jsonwebtoken/jsonwebtoken.github.io#149]
Make it easier to share a URL to jwt.io that contains a web token.  A couple ideas:
- Automatically update the URL with the `?value=token` whenever the token is modified in the editor/viewer.
- Display a shareable URL somewhere on the page that I can copy/paste.

**Comment by sergiorykov** [comment]
Aggreed. Need it too.

I think it will be enough to add button 'Copy URL' which will create url in form of:
jwt.io?alg=HS256&value=a.b.c&secret=asdf&base64=true
jwt.io?alg=RS256&value=a.b.c&publicKey=<urlencode(publickey)>&privateKey=<urlencode(privatekey)>

and support base standalone parameters value/id_token for backward compability.

editable header/payload will be covered automatically.

**Comment by sergiorykov** [comment]
Actually, to check the idea and verify that I've not forget web too much to not be able implement it - I've implemented prototype in my brunch. 

![Copy URL](http://images.devs-on.net/Image/YILizC5DomAnd2Y1-.png)

@woloski can you please to take a look at? 
https://github.com/sergiorykov/jsonwebtoken.github.io/commits/master

**Comment by woloski** [comment]
not a huge fan of pass around urls with secrets

**Comment by sergiorykov** [comment]
Sorry for late response.

Yes, we can by mistake save _real_ secrets. Everyone can. 

Actually I think about it only as a way to represent *working* sample in documentation. We ve'been using local version with Copy URL support since my comment and found it pretty useful to test what's going on several platforms and languages and discuss it (linux/c, android/java, ios/obj-c, win/c#), along with unit tests, of course. Even more - mistakes in protocol (in domain) can be pasted in bug tracker in representative form.

**Comment by sebadoom** [comment]
We do this in the JWT extension _without_ sharing the secrets. I think this is the right approach. We will eventually implement it in the site.

**Comment by sebadoom** [comment]
Partially implemented in 99d1204adcc2fecc8d413ca42f8bf676a3be1e50

We do not share private keys or secrets, only public keys and the token.

**Comment by sebadoom** [comment]
Implemented in stage-6 branch (soon to go live). No secrets are shared, only public keys. Thanks!
