### ISSUE TITLE
When ticking `secret` the token value doesn't update

### ISSUE THREAD

**Issue by catamphetamine** [jsonwebtoken/jsonwebtoken.github.io#220]
subj

**Comment by sebadoom** [comment]
The logic behind the UI is a bit odd but it works like this:
- If change the token or the keys/secret it attempts to verify the token.
- If you change the header or payload it attempts to create a token.

So any changes to the `secret` checkbox cause the code to attempt to verify the token rather than generate it. This is expected.

If you think a different behavior would be more appropriate, describe it here and will review it. Thanks.
