### ISSUE TITLE
Debugger on jwt.io, Signature always verified for Algorithm HS256 ? 

### ISSUE THREAD

**Issue by sreyseng** [jsonwebtoken/jsonwebtoken.github.io#306]
After I paste in the following token:
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTUyNDQ0MjE5OX0.a9b52fBZPUtpmxlOVl2xZtXrxwDdaUqBOmrJQ0ou0lI`

The debugger on the website notes the signature as invalid, which is what I expected, as the "secret" is wrong.

However, after inputting _anything_, or even _nothing_ in the the "secret" field, the debugger on the website indicates the signature is verified. It actively modifies the encoded token to match what I put in the decoded side.

Is this intentional? That is to say, with the debugger, I should not be able to verify an existing token?

**Comment by sebadoom** [comment]
This is intentional. If you paste a token and then change the "secret" a new token is generated using the new secret. Obviously, the new token is verified, since it was created using the secret that was changed. If you want to verify a token against a specific secret, paste the secret first, and then paste the token.

I hope this makes things clearer. If not, please reopen this bug.

**Comment by sreyseng** [comment]
Thanks for expanding on workflow to verify against a specific secret, this makes sense!
