### ISSUE TITLE
Extension window closes when trying to paste something

### ISSUE THREAD

**Issue by sebadoom** [jsonwebtoken/jsonwebtoken.github.io#317]
We need more details from the user, can't reproduce.

**Comment by mastamark** [comment]
I'm personally seeing this on Firefox (68.0.1 (64-bit)) on OS X Mojave and it happens when I change window focus away from the extension window.

Specifically if I have 2 pieces of info I want to paste into the extension, between pasting the first and going to get the 2nd in the clipboard the extension window closes, and on reopen its empty/reset.  I'm not seeing an option to disable that behavior, but perhaps I'm just missing it.
