### ISSUE TITLE
loading shared url always seems to result in 'Invalid Signature'

### ISSUE THREAD

**Issue by jogu** [jsonwebtoken/jsonwebtoken.github.io#351]
If I load the below URL on latest firefox/safari/chrome on macOS 10.13.6, it always shows as 'Invalid signature'.

If I make a trivial edit to the jwt (ie. click into the text box and add a space to end) it shows "Signature Verified". 

https://jwt.io/#debugger-io?token=eyJhbGciOiJFUzI1NiIsImtpZCI6Im1vbyJ9.eyJpYWFhYWFhdCI6MTUzNzA5MzQ5NywiZXhlZWVlcCI6MTUzNzA5NzA5N30.fsvs3UD6zTMWvrQDqXJxzTUfanCO5ZFwRM-NeZuTJx8ICR2Hkn8K9_xzaISxHYV0jXCyuKOc5VJBUsprpMARig&publicKey=-----BEGIN%20PUBLIC%20KEY-----%0AMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEv5jc0O2gWyAa9w4h4iRiAxM4uvqt%0A5psoR%2BmVkFhXRXotqoHcjNVeqrUT1avshwTUgXm20eJ6BPyGDoTHVmKypw%3D%3D%0A-----END%20PUBLIC%20KEY-----%0A

**Comment by jogu** [comment]
Hey @Sambego - thanks for confirming this is a bug.

Do you know if this might get looked at any time soon, or is there any way to change the url to workaround it?

I was thinking to add links to jwt.io when the OpenID conformance suite is generating JWS, but that'll result in me getting a lot of bug reports if jwt.io tells the suite users that all the signatures we've generated are invalid.

**Comment by panva** [comment]
Joseph, i recently updated jwt.io to handle automatically handle fetching keys from the token's `iss` -> `well-known` -> `jwks_uri` when a token is pasted in

See the following debug link, it does not contain the publicKey and yet it resolves it and verifies it.

{code}
https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InIxTGtiQm8zOTI1UmIyWkZGckt5VTNNVmV4OVQyODE3S3gwdmJpNmlfS2MifQ.eyJzdWIiOiJmIiwibm9uY2UiOiIyMjQ1OGMzNjEwMTA4ZDUwZGEyZGMyYWQ4NjUzOGUwOSIsImF0X2hhc2giOiJiR1QtSjVGOENuanF2NXhnSmtxVFhRIiwiYXVkIjoid0wtWHBzdXFnR1BFUVVWOEVVVnl1IiwiZXhwIjoxNTYxMDE3MTY1LCJpYXQiOjE1NjEwMTM1NjUsImlzcyI6Imh0dHBzOi8vZ3VhcmRlZC1jbGlmZnMtODYzNS5oZXJva3VhcHAuY29tIn0.NoIRg6olG7EHkJ6MjYmbuauJK2oYYBO-0l3bHrooRpTPxcT3LQzI3VeTTsxxJjQOl6ErTXKnJahphJjDxilO-5n0XePHfxf0dUzLJatAzYslvJEKtYWGT24AS_bHmvtOdqStmmml4w5d6xIz39rUbMUgNuttuwEWYnfv_l4I-cT3qg_YVnfWYjkL5NCbv3O-M29ICfaQ4HE7u9lGjscDMiE2QFG_Z-M-MHCT7Rmw21znE2wIi_Ac2ym7HEiIBAHdgIO4hypK4QfGRZ_Dc7xMhmA0yxagKABiLHBRMAAFTtN_fAcQzN9GnoVX66jhmPO7hqMuQonjRl0WTmd35-QGKA
{code}

Note there are a few caveats

- both well-known and jwks_uri must support CORS
- it can only handle some algs (it doesn't handle PS512 due to some issues in node-jose and doesn't handle EdDSA because of its lack of support in node-jose), no HS either (as they are forbidden in both OP and RP jwks_uri)

**Comment by jogu** [comment]
Thanks Filip! This is neat, though unfortunately I think it doesn't help with my current use case (client assertions). FYI https://jwt.davetonge.co.uk can do something similar but is a bit more verbose, I don't know if it has the same limitations.

**Comment by panva** [comment]
#404 addresses the issue
