### ISSUE TITLE
Documentation suggests storing JWTs in localStorage

### ISSUE THREAD

**Issue by nflaig** [jsonwebtoken/jsonwebtoken.github.io#409]
I was reading the [Introduction](https://jwt.io/introduction/) page and it worries me  a lot. As described in the documentation it suggests passing the JWTs in a custom header namely `Authorization: Bearer <token>` which implies that you have to store the JWT in localStorage at least in the case where the client is a browser. For native client applications this is not a problem so if I refer to client here I am talking about browsers.

I don't even know where to start here, there are so many issues with this. First of all it is not recommended to store  sensitive information in localStorage and a JWTs are most of the time basically the equivalent of the user credentials in terms of what you can do with them if you gain access to it, so they are VERY sensitive. localStorage makes them vulnerable to [XSS](https://www.owasp.org/index.php/Cross-site_Scripting_%28XSS%29) which means even if your code is secure, any 3rd party library has to be secure as well (they are not) because if not all the tokens belonging to your users can be stolen and you probably wont even notice it. 

Localstorage was not introduced with HTML5 to store tokens so it shouldnt be used for it. OWASP explains most of the issues [here](https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html#local-storage) and their recommendation on this topic is very clear.

If there are still doubts, there is also the option to check how big companies handle this e.g facebook, amazon, google, netflix, etc. If you check the biggest 30-100 websites that are out there you will not find a single one that uses localStorage for tokens or other sensitive information.

Cookies are designed to handle sensitive information by having the `httpOnly` flag and additional security measures like `secure` which does not send them over HTTP. There are many more features I dont want to get into here ([more information](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies)).

Yes, one disadvantage is that cookies are vulnerable to CSRF attacks but there are plenty of well tested [counter measures](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#csrf-defense-recommendations-summary) to this. Therefore, this should not be a reason to avoid using cookies.

Now one reason I think why developers started to use localStorage was because they thought they should sent the token in the `Authorization: Bearer <token>`  which is just a misunderstanding of the concept, mainly OAuth 2.0. This header is intended to be used for server to server communication and thats how it is also used in OAuth 2.0. It is not intended to be used for client to server communication.

I really suggest you change the introduction on your website and do not advertise bad security practices. The practices that come to my mind right now that are worse than storing sensitive information in localStorage is storing user password in plain text and sending credentials over HTTP. But considering the whole javascript ecosystem and how many 3rd party libraries are used within every website nowadays I am not even sure that these practices are worse. Even if all the libraries are secure and not vulnerable to XSS there is still the possibility that a library intentionally publishes malicious code which already happened to many times to keep count of it.

I hope this was clear enough.

### Acceptance criteria
- [x] Stop advertising bad security practices
- [x] Remove the whole `Authorization: Bearer <token>` nonsense from the website or explain that this header should NOT be used if the client is a browser

**Comment by Sambego** [comment]
Hey @nflaig 

Thanks for voicing your concerns. We at Auth0 take security and best practices very seriously. That's why we do not recommend storing tokens or any other sensitive data in local storage. In fact, a lot of our blog posts and getting started documents do mention this.

For example, [our angular quickstart guide](https://auth0.com/docs/quickstart/spa/angular2#restore-login-state-when-app-reloads)

As for the introduction on jwt.io, it does not advocate storing tokens but just explains how they are commonly used. I will try to include a paragraph stating they should not be saved in local storage, just for clarity.

We're always looking for the best way to handle authentication for any platform and use case. We [recently released a new JavaScript SDK](https://auth0.com/blog/introducing-auth0-single-page-apps-spa-js-sdk/) that implements OAuth 2.0's PKCE flow. This will make requesting tokens more secure when working with single-page applications.

I hope this eases your concerns.

**Comment by Sambego** [comment]
An extra warning to not store tokens in local storage has been added https://github.com/jsonwebtoken/jsonwebtoken.github.io/commit/4bd54b6a81107e403469555bbf9f430a80ecfe8e

**Comment by nflaig** [comment]
Hi @Sambego 

Thanks for your response and the note you already added. I also want to add here that I really appreciate the  great work that you and everyone at Auth0 are doing.

I also totally agree with you that you in fact did not advocate to store tokens in localStorage but using the `Authorization: Bearer <token>` schema in a context of browser implies that becasue they only way you could set this header from the browser would be by using local or session storage. In this [introduction](https://auth0.com/learn/json-web-tokens/) you explicitly use a browser as example together with the Authorization header.

The main reason why I created this issue was because I saw so many tutorials that are using localStorage to store tokens because think they have to use the Authorization header which is fine but not in the context of a browser. I think even tutorial or example apps should advocate good practices so updating the docs with that note you added is already good start, thanks for that.

Adding some note [here](https://auth0.com/learn/json-web-tokens/) would be also great.

**Comment by Sambego** [comment]
Hey @nflaig 

I agree a lot of tutorials still suggest to use local storage to store tokens. This has been a common practice in the past, but since has shown a lot of vulnerabilities. 

Using the `Authorization: Bearer <token>` does not have to mean you should store the tokens somewhere persistently. You can, for example, fetch the tokens and keep them in memory. For not having to authenticate on every visit, you can fetch them with a [silent authorization request](https://auth0.com/docs/api-auth/tutorials/silent-authentication), and save them again in memory.

I'll contact the people responsible for that page you linked to have that changed.

Thanks again for the feedback!

**Comment by nflaig** [comment]
Hi @Sambego 

You are right, using the header does not always mean the tokens are persisted in localStorage but a lot of implementations do it that's the problem.

I am not that familiar with security implications if you keep tokens in memory on the client side but it seems vulnerable to XSS but not as bad as localStorage since you still need to know the implementation details. 

 Regarding the `Authorization: Bearer <token>` schema it seems sufficient to me if the note to not store tokens in localStorage is added which you already did.

Thanks for your great work!

**Comment by Sambego** [comment]
👍 cool, I'll close this issue then.
