### ISSUE TITLE
Text Snippets selected in the web UI are submitted to heapanalytics.com

### ISSUE THREAD

**Issue by jamesmelville** [jsonwebtoken/jsonwebtoken.github.io#462]
Quote from the site:
> We do not record tokens, all validation and debugging is done on the client side.

Yet when I select text on the webpage I can see in the network log that the text selected is sent to heapanalytics.com in the x1 query parameter. The data sent seems to be limited to 64 characters, but a user selecting parts of their token step by step, or selecting their secret can easily leak critical information here, which the site claims not to do.

It seems these elements should be tagged `heap-ignore="true"` per https://docs.heap.io/docs/web#sensitive-data

**Comment by Sambego** [comment]
Thanks for pointing this out! The JWT debugger is now ignored by Heap Analytics.

**Comment by jamesmelville** [comment]
Well done for fixing it quickly. Will you also scrub this data from the analytics system?

**Comment by Sambego** [comment]
I can assure you that this data is not used in any way, and tracking the highlighted text is a side-effect of the service. The person responsible for this analytics service was under the impression that the debugger was ignored by default by Heap, since the script ignores all text input fields by default. Unfortunately, the debugger uses CodeMirror which uses some other HTML elements instead of text inputs.

I will follow up with the person responsible to make sure this data is erased from the analytics service.

Thanks again for reporting this 💪
