### ISSUE TITLE
jwt.io is spamming my GitHub API 

### ISSUE THREAD

**Issue by JoeMarkov** [jsonwebtoken/jsonwebtoken.github.io#487]
Hi

I love jwt.io but when I recently open it using Fiddler I was surprised with the amount of GitHub API requests that is made under the hood (like 100 requests) that all get the same response from GitHub.

**HTTP/1.1 403 rate limit exceeded**

Failed to load resource: the server responded with a status of 403 (rate limit exceeded)
index.js:443 Failed to get GitHub stars count for repository, is the repository URL OK?  Object

Is this really necessary to do?

**Comment by Sambego** [comment]
Hey @JoeMarkov, we're fetching the number of stars on GitHub for each library listed on jwt.io, and sometimes this runs into the rate limit of the GitHub API :)

**Comment by JoeMarkov** [comment]
Thanks for replying, sure I understand that.

But as JWT.io is a soo popular and a frequently loaded page, perhaps doing that on the backend and cache those stars? 

I guess the stars does not change so often :-)

ps, just my inner performance geek who is worried here :-)

**Comment by panva** [comment]
FWIW 

- stars do change often
- you're right, they don't need to be always up to date

@Sambego can we fetch these with an authenticated (with a personal access token) github request in the backend and cache it for x hours or a day?

**Comment by Sambego** [comment]
We are caching the stars for a week in local storage. If we have cached data available, we won't do the actual API request, but use the cached data instead. I could maybe improve on catching the errors thrown because of a failed API request and keep it out of the console, but it will always show up in the networks tab of your developer tools.

We deliberately do not use any kind of back-end with jwt.io. We often handle sensitive tokens and want to guarantee the user we're not doing anything invisible with those. Everything is done on the front-end, and tokens never leave your browser. 

I know that's unrelated to the libraries, but it's about the message we're sending to users :)

**Comment by Sambego** [comment]
@panva, that would require us to make a user authenticate with GitHub, just for some stars. I don't think that's feasible.

**Comment by panva** [comment]
@Sambego I obviously didn't mean the end-user would need to authenticate. We just need a personal access token of yours or mine.

**Comment by BlackthornYugen** [comment]
Can we make this a feature request to keep track of calls to this api client side so we limit the requests client side? I hit the rate limit constantly beacuse when I'm debugging I have caching off. For now I'll just disable the github calls all together for my fork.

**Comment by BlackthornYugen** [comment]
It looks like it's hitting their server with 47 requests and they rate limit at 60. So it's when I refresh the page that I end up exceeding the limit. So for most people they won't hit it but it's still probably unnessiary to put so much traffic to api.github.com for users that don't scroll through the libraries.

**Comment by Sambego** [comment]
This is fixed by #506. The frontend does not do any requests to the GH API anymore.
