### ISSUE TITLE
Regular base64 encoding no longer works

### ISSUE THREAD

**Issue by wizofaus** [jsonwebtoken/jsonwebtoken.github.io#501]
I used to use jwt.io to verify tokens that were generated by a backend that (incorrectly) used regular base64 encoding instead of base64url encoding, and it worked just fine, but no longer does.
Is there any case for restoring this?

**Comment by Sambego** [comment]
Are you talking about using a signature with a `base64` endocding instead of a `base64URL` encoding? We still validate those even if you're using the wrong encoding.

If you verify a token with a `base64` encoded signature, the debugger will show the `Invalid JWT` error, as technically it's not a valid token. 
<img width="200" alt="Screenshot 2020-11-16 at 09 58 11" src="https://user-images.githubusercontent.com/1453781/99232887-c83de300-27f2-11eb-98d1-d63b05c3093b.png">

If the signature is not valid (regardless of the encoding), we show the `invalid signature` error.
<img width="268" alt="Screenshot 2020-11-16 at 09 57 02" src="https://user-images.githubusercontent.com/1453781/99232945-ddb30d00-27f2-11eb-83c0-ce5ce92723dc.png">

Together with those errors, we also show some warnings, but these also don't stop the debugger from verifying tokens.

**Comment by wizofaus** [comment]
Ah, so if it says Invalid JWT the signature is still OK? That's fine then, can close this if so.
