### ISSUE TITLE
Fix tooltip for unix timestamps

### ISSUE THREAD

**Issue by bertyhell** [jsonwebtoken/jsonwebtoken.github.io#552]
Currently unix timestamps are interpreted as seconds which causes the tooltip date to be something like:
```Tue Aug 16 53701 08:34:40 GMT+0200 (Central European Summer Time)```

![image](https://user-images.githubusercontent.com/1710840/134689765-3610d9b1-4cef-4a41-b6e6-55d2f360f7df.png)

Is there a way to change this? or is this done by CodeMirror?

I'm thinking something like: if year > 10000 => change the input to input / 1000

I had a look into the code, but i don't see the tooltip code or CodeMirror code anywhere. The closes i've gotten is here:
https://github.com/jsonwebtoken/jsonwebtoken.github.io/blob/dc37a34ad754693f5eaeece0c2f10a6da1821b39/views/token-editor-common.pug#L23

**Comment by Sambego** [comment]
Hey @bertyhell, the JWT [specification](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4) states the expiry date to be a NumericDate, which is the number of seconds not milliseconds since 1970-01-01T00:00:00Z UTC. 

NumericDate
> A JSON numeric value representing the number of seconds from
1970-01-01T00:00:00Z UTC until the specified UTC date/time,
ignoring leap seconds. This is equivalent to the IEEE Std 1003.1,
2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
which each day is accounted for by exactly 86400 seconds, other
than that non-integer values can be represented. See RFC 3339
[RFC3339] for details regarding date/times in general and UTC in
particular.
